#!/usr/bin/python3

import glob
import os
import yaml
import sys

def append_entry(entries, doc):
    entry = None
    if 'result' in doc and '맞춤법 검사' in doc['result']:
        if '제외' not in doc['result']['맞춤법 검사']:
            entry = doc['result']['맞춤법 검사']
    if entry is not None:
        keys = entry.keys()
        REPLACE = {'표제어':'word', '품사':'pos', '속성':'props'}
        e = {}
        for k in keys:
            if k in REPLACE:
                e[REPLACE[k]] = entry[k]
        if 'word' not in e or 'pos' not in e:
            print(entry)
            print(e)
            print(doc)
            abort()
        if e['pos'] == '의존 명사':
            e['pos'] = '명사'
        elif e['pos'] == '보조 동사':
            e['pos'] = '동사'
        elif e['pos'] == '보조 형용사':
            e['pos'] = '형용사'
        entries.append(e)

def process_file(filename, entries):
    documents = yaml.load_all(open(filename))
    for k in documents:
        append_entry(entries, k)

def output_file(filename, entries):
    entries.sort(key=lambda x : x['word'])
    with open(filename, 'w') as outfile:
        outfile.write('# 자동으로 생성된 파일입니다. 직접 편집하지 마십시오.\n')
        outfile.write('# This file is auto generated. Do not edit this file.\n')
        outfile.write('# The file is licensed under the GPL version 3 or later.\n')
        yaml_entry = {'entries': entries}
        yaml.dump(yaml_entry, outfile, allow_unicode=True, default_flow_style=False, indent=2)
    print(filename)

def find_and_save(dir, filename):
    yaml_filenames = glob.glob(dir + '/*.yaml')
    entries = []
    print('Total %d files...' % len(yaml_filenames))
    count = 0
    for yaml_filename in yaml_filenames:
        process_file(yaml_filename, entries)
        count += 1
        sys.stdout.write('%d...' % count)
        sys.stdout.flush()
    sys.stdout.write('\n')
    output_file(filename, entries)


def gen_custom_words():
    path = './entries/custom-words.txt'
    outputpath = './entries/custom-words.yaml'
    if not os.path.exists(path):
        return
    words = []
    with open(path, 'rt') as fp:
        words = [line.strip() for line in fp.readlines()]

    firstput = True
    with open(outputpath, 'wt') as wp:
        for word in words:
            if not firstput:
                wp.write('---\n')

            buf = f'''000_KEYWORD: {word}__명사__001
import:
  seorenn:
    구분: 단어
    표제어: {word}
    품사: 명사
    라이선스: MPL 1.1/GPL 2.0/LGPL 2.1
result:
  맞춤법 검사:
    표제어: {word}
    품사: 명사'''
            wp.write(buf)
            wp.write('\n')
            
            firstput = False


if __name__ == '__main__':
    dir = './entries'
    outfile = '../dict-ko-data.yaml'
    gen_custom_words()
    find_and_save(dir, outfile)
